19 daily log r
Bulk-bros/stattrack pull request #38
Opened 2022-10-13 18:16 UTC by Richileu-A-Bailey

2022-10-13 18:48 UTC, falniir commented on stattrack/pubspec.yaml
> +    - assets/foodstockpic.jpg
The following file should be added to assets/images and not to the root of the directory. This should fix also fix the workflow error.

![image](https://user-images.githubusercontent.com/77648731/195680624-3d540fc8-cbd9-407d-b764-02d88561ff9a.png)


![DogSmileShyboosGIF](https://user-images.githubusercontent.com/77648731/195680904-ae3ead33-4ba9-461c-8c41-30cc5e44de81.gif)

2022-10-13 18:49 UTC, falniir reviewed
https://github.com/Bulk-bros/stattrack/pull/38/files#r995003053

2022-10-14 22:13 UTC, falniir commented
![FridayPaydayGIF](https://user-images.githubusercontent.com/77648731/195951515-a7249435-0b5f-46b8-ae24-71034cf6801e.gif)

2022-10-16 20:15 UTC, jKm00 commented
meal card should be clickable (just print something to the terminal, later it will redirect to a new page)

2022-10-16 20:15 UTC, jKm00 requested changes
meal card should be clickable (just print something to the terminal, later it will redirect to a new page)

2022-10-21 19:52 UTC, merged